### ISSUE TITLE
pip install pyspecs fails

### ISSUE THREAD

**Issue by robert-dzikowski** [mdwhatcott/pyspecs#18]
Hi.
I know that it was corrected in master but version used by pip still has print problem:
pip install pyspecs
Collecting pyspecs
  Downloading pyspecs-2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\WINDOWS\TEMP\pip-build-ua7ehn77\pyspecs\setup.py", line 2, in <module>
        import pyspecs
      File "C:\WINDOWS\TEMP\pip-build-ua7ehn77\pyspecs\pyspecs\__init__.py", line 3, in <module>
        from pyspecs._reporting import ConsoleReporter
      File "C:\WINDOWS\TEMP\pip-build-ua7ehn77\pyspecs\pyspecs\_reporting.py", line 61
        print problem
                    ^
    SyntaxError: Missing parentheses in call to 'print'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\WINDOWS\TEMP\pip-build-ua7ehn77\pyspecs\

I use Python 3.6.0

**Comment by dannypurcell** [comment]
looks like this is still an issue, is this project still maintained?
If so, is there anything blocking the latest from releasing?

**Comment by mdwhatcott** [comment]
@dannypurcell - I haven't touched it for quite some time and don't have any intention to get back into it. @magmax was the last to touch the code, and that was in 2016...
